line-length = 100
indent-width = 4
target-version = "py312"
respect-gitignore = true

# Include all Python files in eyepop/ and tests/
include = ["eyepop/**/*.py", "tests/**/*.py"]

# Standard exclusions
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "*.egg-info",
]

[lint]
select = ["E4", "E7", "E9", "F", "B", "D", "I001"]
ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in __init__
    "D202", # Blank line after docstring
    "F403", # wild card imports is fine for now
    "F405", # consequence of wildcard imports
    "B008", # Function call in argument
]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"__init__.py" = [
    "D104", # init doesn't need docstring
    "F401", # init can have unused imports
    "I001", # ignore sorting of imports
]
