line-length = 100
indent-width = 4
target-version = "py312"
respect-gitignore = true

include = [
    "tests/test_compute_*.py", 
    "eyepop/compute/*", 
]

exclude = ["*"]

[lint]
select = ["E4", "E7", "E9", "F", "B", "D", "I001"]
ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D107", # Missing docstring in __init__
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D202", # Blank line after docstring
    "F403", # wild card imports is fine for now
    "F405", # consequence of wildcard imports.
    "B008", # Function call in argument
]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"__init__.py" = [
    "D104", # init doesn't need docstring
    "F401", # init can have unused imports
    "I001", # ignore sorting of imports
]
